export const BRANDS = {
  hc: {
    id: 'hc',
    name: 'Hispanos Comunidad',
    nameShort: 'HC',
    route: '/',
    domain: 'hispanoscomunidad.com',
    color: 'var(--hc-navy)',
    colorLight: 'var(--hc-ivory)',
    accent: 'var(--hc-brass)',
    tagline_es: 'Más que servicios, somos comunidad.',
    tagline_en: 'More than services. We are community.',
  },

  bonanza: {
    id: 'bonanza',
    name: 'Bonanza Quick Loans',
    nameShort: 'Bonanza',
    route: '/bonanza',
    domain: 'bonanzaquickloans.com',
    color: 'var(--bonanza-gold)',
    colorLight: 'var(--bonanza-light)',
    colorDark: 'var(--bonanza-dark)',
    accent: 'var(--bonanza-mid)',
    tagline_es: 'Tu préstamo fácil. En menos de 24 horas.',
    tagline_en: 'Your fast loan. In less than 24 hours.',
    description_es: 'Préstamos personales, sobre título y para negocios. Sin SSN, sin historial, en tu idioma.',
    description_en: 'Personal, title, and business loans. No SSN, no credit history required, in your language.',
    stats: {
      loans: '20,000+',
      amount: '$28.9M',
      years: '13',
      approval: '24h',
    },
  },

  zivo: {
    id: 'zivo',
    name: 'Zivo Insurance',
    nameShort: 'Zivo',
    route: '/zivo',
    domain: 'zivoinsurance.com',
    color: 'var(--zivo-teal)',
    colorLight: 'var(--zivo-light)',
    colorDark: 'var(--zivo-dark)',
    accent: 'var(--zivo-mid)',
    tagline_es: 'Seguro que entiendes. Protección que mereces.',
    tagline_en: 'Insurance you understand. Protection you deserve.',
    description_es: 'Seguros de auto, comercial, hogar y vida. Sin seguro social. Autorizado en SC y NC desde 2018.',
    description_en: 'Auto, commercial, home and life insurance. No social security number required. Licensed in SC and NC since 2018.',
    carriers: ['Progressive', 'Trexis', 'Gainsco'],
    stats: {
      households: '5,000+',
      states: 'SC + NC',
      since: '2018',
      status: 'Diamond Carrier',
    },
  },

  media: {
    id: 'media',
    name: 'HC Business & Media',
    nameShort: 'HC Media',
    route: '/media',
    domain: 'institutoeducate.com',
    color: 'var(--media-lilac)',
    colorLight: 'var(--media-light)',
    colorDark: 'var(--media-dark)',
    accent: 'var(--media-mid)',
    tagline_es: 'Estrategia, marketing, tecnología y educación — para negocios latinos.',
    tagline_en: 'Strategy, marketing, technology and education — for Latino businesses.',
    description_es: 'Agencia de marketing, estudio de producción, plataforma de apps, talleres y consultoría de negocios.',
    description_en: 'Marketing agency, production studio, app platform, workshops and business consulting.',
    services_es: ['Agencia de Marketing Digital', 'Estudio de Producción', 'HC Business 360 / Órbita', 'Ruta Empresarial', 'Consultoría CLARITY', 'Shows y Contenido'],
    services_en: ['Digital Marketing Agency', 'Production Studio', 'HC Business 360 / Órbita', 'Ruta Empresarial', 'CLARITY Consulting', 'Shows & Content'],
  },

  unidos: {
    id: 'unidos',
    name: 'Hispanics United of SC',
    nameShort: 'Hispanics United',
    route: '/unidos',
    domain: 'hispanicsunitedsc.com',
    color: 'var(--unidos-green)',
    colorLight: 'var(--unidos-light)',
    colorDark: 'var(--unidos-dark)',
    accent: 'var(--unidos-mid)',
    tagline_es: 'Construido por la comunidad. Financiado por cada transacción.',
    tagline_en: 'Built by the community. Funded by every transaction.',
    description_es: 'Organización sin fines de lucro autofinanciada. Cada préstamo, cada póliza, cada contrato apoya a familias latinas en Carolina del Sur.',
    description_en: 'Self-funded nonprofit. Every loan, every policy, every contract supports Latino families in South Carolina.',
    stats: {
      families: '23,000+',
      clients: '3,000+',
      years: '14',
      screenings: '5,000+',
      graduates: '2,000+',
      reach: '50,000+',
    },
    partners: ['Bon Secours', 'Anderson School District'],
  },
};

export const PILLARS = [
  BRANDS.bonanza,
  BRANDS.zivo,
  BRANDS.media,
  BRANDS.unidos,
];
