export const EVENTS_CONFIG = {
  categories: [
    { id: 'all',        label_es: 'Todos',          label_en: 'All',           color: 'var(--hc-navy)' },
    { id: 'health',     label_es: 'Salud',          label_en: 'Health',        color: 'var(--unidos-green)' },
    { id: 'workshop',   label_es: 'Talleres',       label_en: 'Workshops',     color: 'var(--media-lilac)' },
    { id: 'networking', label_es: 'Networking',     label_en: 'Networking',    color: 'var(--bonanza-gold)' },
    { id: 'community',  label_es: 'Comunidad',      label_en: 'Community',     color: 'var(--zivo-teal)' },
    { id: 'ruta',       label_es: 'Ruta Empresarial', label_en: 'Ruta Empresarial', color: 'var(--media-mid)' },
  ],
};

export const SAMPLE_EVENTS = [
  {
    id: 'health-day-cherrydale-apr-2026',
    slug: 'dia-salud-cherrydale-abril-2026',
    title_es: 'Día de Salud con Bon Secours',
    title_en: 'Health Day with Bon Secours',
    desc_es: 'Consultas médicas gratuitas, vacunas, orientación de salud y exámenes preventivos. Sin importar tu estatus migratorio. Atención en español.',
    desc_en: 'Free medical consultations, vaccines, health guidance, and preventive screenings. Regardless of immigration status. Service in Spanish.',
    date: '2026-04-05',
    time_es: '9:00 AM – 2:00 PM',
    time_en: '9:00 AM – 2:00 PM',
    location: '2327 North Pleasantburg Drive, Suite A · Cherrydale · Greenville, SC 29609',
    location_short: 'Cherrydale · Greenville',
    category: 'health',
    partner: 'Bon Secours',
    free: true,
    capacity: 200,
    image: '/images/community/health-days/bon-secours-blue-bus.jpg',
    whatsapp_msg_es: '¡Hola! Quiero registrarme para el Día de Salud con Bon Secours el 5 de abril.',
    whatsapp_msg_en: 'Hi! I want to register for the Health Day with Bon Secours on April 5th.',
  },
  {
    id: 'ruta-empresarial-finanzas-apr-2026',
    slug: 'ruta-empresarial-finanzas-abril-2026',
    title_es: 'Ruta Empresarial — Taller de Finanzas',
    title_en: 'Ruta Empresarial — Finance Workshop',
    desc_es: 'Aprende a manejar el flujo de caja, crear un presupuesto real y entender los números de tu negocio. Taller práctico con ejercicios reales y asesoría personalizada.',
    desc_en: 'Learn to manage cash flow, create a real budget, and understand your business numbers. Practical workshop with real exercises and personalized guidance.',
    date: '2026-04-12',
    time_es: '10:00 AM – 1:00 PM',
    time_en: '10:00 AM – 1:00 PM',
    location: '1415 Laurens Road, Suite B · Greenville, SC 29609',
    location_short: 'Sede Principal · Greenville',
    category: 'ruta',
    free: true,
    capacity: 40,
    image: '/images/community/workshops/ruta-empresarial.jpg',
    whatsapp_msg_es: '¡Hola! Quiero inscribirme en el Taller de Finanzas de Ruta Empresarial el 12 de abril.',
    whatsapp_msg_en: 'Hi! I want to register for the Ruta Empresarial Finance Workshop on April 12th.',
  },
  {
    id: 'networking-hc-apr-2026',
    slug: 'networking-empresarial-hc-abril-2026',
    title_es: 'Networking Empresarial HC',
    title_en: 'HC Business Networking',
    desc_es: 'Conecta con otros empresarios latinos de Upstate SC. Presenta tu negocio, construye alianzas reales, y descubre oportunidades de crecimiento dentro de la red HC.',
    desc_en: 'Connect with other Latino entrepreneurs in Upstate SC. Present your business, build real alliances, and discover growth opportunities within the HC network.',
    date: '2026-04-18',
    time_es: '6:00 PM – 9:00 PM',
    time_en: '6:00 PM – 9:00 PM',
    location: '1415 Laurens Road, Suite B · Greenville, SC 29609',
    location_short: 'Sede Principal · Greenville',
    category: 'networking',
    free: true,
    capacity: 80,
    image: '/images/community/events/networking-hc.jpg',
    whatsapp_msg_es: '¡Hola! Quiero reservar mi lugar en el Networking Empresarial HC del 18 de abril.',
    whatsapp_msg_en: 'Hi! I want to reserve my spot at the HC Business Networking on April 18th.',
  },
  {
    id: 'ruta-empresarial-marketing-may-2026',
    slug: 'ruta-empresarial-marketing-mayo-2026',
    title_es: 'Ruta Empresarial — Marketing Digital',
    title_en: 'Ruta Empresarial — Digital Marketing',
    desc_es: 'Aprende a usar las redes sociales para hacer crecer tu negocio. Estrategia de contenido, Meta Ads básicos, y cómo convertir seguidores en clientes reales.',
    desc_en: 'Learn to use social media to grow your business. Content strategy, basic Meta Ads, and how to convert followers into real clients.',
    date: '2026-05-10',
    time_es: '10:00 AM – 1:00 PM',
    time_en: '10:00 AM – 1:00 PM',
    location: '1415 Laurens Road, Suite B · Greenville, SC 29609',
    location_short: 'Sede Principal · Greenville',
    category: 'ruta',
    free: true,
    capacity: 40,
    image: '/images/community/workshops/ruta-marketing.jpg',
    whatsapp_msg_es: '¡Hola! Quiero inscribirme en el Taller de Marketing Digital de Ruta Empresarial en mayo.',
    whatsapp_msg_en: 'Hi! I want to register for the Ruta Empresarial Digital Marketing Workshop in May.',
  },
  {
    id: 'health-day-spartanburg-may-2026',
    slug: 'dia-salud-spartanburg-mayo-2026',
    title_es: 'Día de Salud — Spartanburg',
    title_en: 'Health Day — Spartanburg',
    desc_es: 'Llevamos los servicios de salud gratuitos a Spartanburg. Consultas, vacunas y orientación médica para toda la familia. Alianza Bon Secours.',
    desc_en: 'We bring free health services to Spartanburg. Consultations, vaccines, and medical guidance for the whole family. Bon Secours alliance.',
    date: '2026-05-17',
    time_es: '9:00 AM – 2:00 PM',
    time_en: '9:00 AM – 2:00 PM',
    location: '1481 Asheville Highway, Suite A · Spartanburg, SC 29303',
    location_short: 'Spartanburg, SC',
    category: 'health',
    partner: 'Bon Secours',
    free: true,
    capacity: 150,
    image: '/images/community/health-days/health-day-spartanburg.jpg',
    whatsapp_msg_es: '¡Hola! Quiero registrarme para el Día de Salud en Spartanburg el 17 de mayo.',
    whatsapp_msg_en: 'Hi! I want to register for the Health Day in Spartanburg on May 17th.',
  },
  {
    id: 'community-celebration-jun-2026',
    slug: 'celebracion-comunidad-junio-2026',
    title_es: 'Celebración de Comunidad HC',
    title_en: 'HC Community Celebration',
    desc_es: 'Celebramos juntos 13 años de comunidad. Música, comida, reconocimientos, y el calor de nuestra gente reunida. Abierto a toda la familia.',
    desc_en: 'We celebrate together 13 years of community. Music, food, recognition, and the warmth of our people gathered. Open to the whole family.',
    date: '2026-06-07',
    time_es: '4:00 PM – 9:00 PM',
    time_en: '4:00 PM – 9:00 PM',
    location: '1415 Laurens Road, Suite B · Greenville, SC 29609',
    location_short: 'Sede Principal · Greenville',
    category: 'community',
    free: true,
    capacity: 300,
    image: '/images/community/events/celebracion-comunidad.jpg',
    whatsapp_msg_es: '¡Hola! Quiero reservar mi lugar en la Celebración de Comunidad HC en junio.',
    whatsapp_msg_en: 'Hi! I want to reserve my spot at the HC Community Celebration in June.',
  },
];
