export const SHOWS = [
  {
    id: 'hispanos-que-inspiran',
    name: 'Hispanos que Inspiran',
    slug: 'hispanos-que-inspiran',
    tagline_es: 'Historias que mueven. Personas que inspiran.',
    tagline_en: 'Stories that move. People who inspire.',
    description_es: 'Historias reales de latinos que han transformado sus vidas y sus comunidades en Upstate South Carolina y más allá.',
    description_en: 'Real stories of Latinos who have transformed their lives and communities in Upstate South Carolina and beyond.',
    cover: '/images/shows/hispanos-que-inspiran/cover.jpg',
    color: 'var(--hc-brass)',
  },
  {
    id: 'que-onda-gvl',
    name: 'Qué Onda GVL',
    slug: 'que-onda-gvl',
    tagline_es: 'Lo que pasa en Greenville, en tu idioma.',
    tagline_en: 'What happens in Greenville, in your language.',
    description_es: 'Noticias locales, cultura y lo que importa en Greenville — contado con la perspectiva de la comunidad latina.',
    description_en: 'Local news, culture, and what matters in Greenville — told from the Latino community perspective.',
    cover: '/images/shows/que-onda-gvl/cover.jpg',
    color: 'var(--zivo-teal)',
  },
  {
    id: 'recalculando-ruta',
    name: 'Recalculando Ruta',
    slug: 'recalculando-ruta',
    tagline_es: 'Cuando el camino cambia, recalculamos juntos.',
    tagline_en: 'When the road changes, we recalculate together.',
    description_es: 'Educación financiera práctica y estrategia de negocios para emprendedores latinos que quieren crecer con claridad.',
    description_en: 'Practical financial education and business strategy for Latino entrepreneurs who want to grow with clarity.',
    cover: '/images/shows/recalculando-ruta/cover.jpg',
    color: 'var(--media-lilac)',
  },
  {
    id: 'la-parranda',
    name: 'La Parranda',
    slug: 'la-parranda',
    tagline_es: 'Cultura, música y celebración latina.',
    tagline_en: 'Latino culture, music, and celebration.',
    description_es: 'El show donde celebramos lo mejor de nuestra cultura — música, tradiciones y la alegría de nuestra comunidad.',
    description_en: 'The show where we celebrate the best of our culture — music, traditions, and the joy of our community.',
    cover: '/images/shows/la-parranda/cover.jpg',
    color: 'var(--bonanza-gold)',
  },
  {
    id: 'el-cotorreo',
    name: 'El Cotorreo',
    slug: 'el-cotorreo',
    tagline_es: 'La conversación sin filtros de la comunidad.',
    tagline_en: 'The unfiltered conversation of the community.',
    description_es: 'Conversaciones auténticas, temas que importan y la perspectiva latina sin editar.',
    description_en: 'Authentic conversations, topics that matter, and the unedited Latino perspective.',
    cover: '/images/shows/el-cotorreo/cover.jpg',
    color: 'var(--unidos-green)',
  },
  {
    id: 'un-cafe-con-paola',
    name: 'Un Café con Paola',
    slug: 'un-cafe-con-paola',
    tagline_es: 'Conversaciones que cambian perspectivas.',
    tagline_en: 'Conversations that change perspectives.',
    description_es: 'Paola Rogers en conversación directa con empresarios, líderes y personas que están construyendo algo importante.',
    description_en: 'Paola Rogers in direct conversation with entrepreneurs, leaders, and people building something important.',
    cover: '/images/shows/un-cafe-con-paola/cover.jpg',
    color: 'var(--hc-lilac)',
  },
  {
    id: 'conectado',
    name: 'Conectado',
    slug: 'conectado',
    tagline_es: 'La comunidad, siempre conectada.',
    tagline_en: 'The community, always connected.',
    description_es: 'El show que mantiene a la comunidad latina de Upstate informada, conectada y empoderada.',
    description_en: 'The show that keeps the Upstate Latino community informed, connected, and empowered.',
    cover: '/images/shows/conectado/cover.jpg',
    color: 'var(--hc-navy)',
  },
];
