export const TEAM = [
  {
    id: 'paola',
    name: 'Paola Rogers',
    role_es: 'Fundadora y Presidenta',
    role_en: 'Founder & President',
    brand: 'hc',
    brandColor: 'var(--hc-brass)',
    bio_es: 'Con más de 13 años sirviendo a la comunidad latina empresarial en Upstate South Carolina, Paola construyó un ecosistema que va desde préstamos hasta tecnología, seguros, educación y medios. Su visión: que ningún empresario latino camine su negocio solo.',
    bio_en: 'With over 13 years serving the Latino business community in Upstate South Carolina, Paola built an ecosystem spanning loans, technology, insurance, education, and media. Her vision: no Latino entrepreneur should walk their business journey alone.',
    avatar: '/images/team/avatars/paola-portrait.png',
    avatarScene: '/images/team/avatars/paola-bus-hero.png',
    photo: '/images/team/paola-rogers.jpg',
  },
  {
    id: 'dayana',
    name: 'Dayana',
    role_es: 'CEO — Operaciones Globales',
    role_en: 'CEO — Global Operations',
    brand: 'hc',
    brandColor: 'var(--hc-navy)',
    bio_es: 'Lidera las operaciones estratégicas del ecosistema HC. Su enfoque está en la ejecución de alto nivel y en asegurar que cada cliente reciba el apoyo necesario para crecer.',
    bio_en: 'Leads the strategic operations of the HC ecosystem, focused on high-level execution and ensuring every client receives the support they need to grow.',
    avatar: '/images/team/avatars/dayana-standing.png',
    avatarScene: '/images/team/avatars/dayana-driving-2.png',
  },
  {
    id: 'amili',
    name: 'Amili',
    role_es: 'Líder de Marketing — HC Business & Media',
    role_en: 'Marketing Leader — HC Business & Media',
    brand: 'media',
    brandColor: 'var(--media-lilac)',
    bio_es: 'Dirige todas las estrategias de marketing, contenido y campañas digitales. Su equipo hace crecer la visibilidad y el alcance de cada negocio cliente mes a mes.',
    bio_en: 'Leads all marketing strategies, content, and digital campaigns. Her team grows the visibility and reach of every client business month by month.',
    avatar: '/images/team/avatars/amili-portrait.png',
    avatarScene: '/images/team/avatars/amili-portrait.png',
  },
  {
    id: 'adriana',
    name: 'Adriana',
    role_es: 'Líder de Campo — Bonanza Quick Loans',
    role_en: 'Field Leader — Bonanza Quick Loans',
    brand: 'bonanza',
    brandColor: 'var(--bonanza-gold)',
    bio_es: 'Especialista en financiamiento para la comunidad latina. Ayuda a familias y dueños de negocios a acceder al capital que necesitan para expandir y crecer.',
    bio_en: 'Specialist in financing for the Latino community, helping families and business owners access the capital they need to expand and grow.',
    avatar: '/images/team/avatars/adriana-portrait.png',
    avatarScene: '/images/team/avatars/adriana-working.png',
  },
  {
    id: 'andrea',
    name: 'Andrea',
    role_es: 'Líder de Seguros — Zivo Insurance',
    role_en: 'Insurance Leader — Zivo Insurance',
    brand: 'zivo',
    brandColor: 'var(--zivo-teal)',
    bio_es: 'Protege los negocios y familias de los clientes HC con soluciones de seguros diseñadas para la comunidad latina. Garantiza que ningún imprevisto detenga lo que están construyendo.',
    bio_en: 'Protects HC client businesses and families with insurance solutions designed for the Latino community, ensuring no unexpected event stops what they are building.',
    avatar: '/images/team/avatars/andrea-portrait.png',
    avatarScene: '/images/team/avatars/andrea-portrait.png',
  },
  {
    id: 'dollys',
    name: 'Dollys',
    role_es: 'Soluciones al Cliente — HC Business & Media',
    role_en: 'Client Solutions — HC Business & Media',
    brand: 'media',
    brandColor: 'var(--media-lilac)',
    bio_es: 'El puente entre el cliente y el equipo HC. Asegura que cada interacción y entrega refleje la calidad y el cuidado que caracteriza a HC en cada punto de contacto.',
    bio_en: 'The bridge between the client and the HC team, ensuring every interaction and delivery reflects the quality and care that characterizes HC at every touchpoint.',
    avatar: '/images/team/avatars/dollys-portrait.png',
    avatarScene: '/images/team/avatars/dollys-portrait.png',
  },
];

export const TEAM_ASSETS = {
  groupPhoto: '/images/team/avatars/team-group-5.png',
  trio: '/images/team/avatars/team-trio.png',
  busHero: '/images/team/avatars/paola-bus-hero.png',
};
